#
PREFIX = ./

#################################################
########            Cleaning             ########
#################################################
clean:
	rm -f *.log
	rm -f *.aux
	rm -f *.idx
	rm -f *.toc
	rm -f *.out.ps
	rm -f *.lof
	rm -f *.lot
#
